### PR TITLE
container/ring: fix data race on r.full

### LINKED ISSUE #140: container/ring: data race detected on ring.full
I compiled `hubble` (at ref c7f6953b6f178b68a23eaea6f2db32ec291fa214) with the `-race` flag and ran into a data race while running `hubble serve --max-flows 255`:
```
WARNING: DATA RACE
Read at 0x00c0006801b8 by goroutine 80:
  github.com/cilium/hubble/pkg/server.newRingReader()
      /home/vagrant/go/src/github.com/cilium/hubble/pkg/container/ring.go:83 +0x3ff
  github.com/cilium/hubble/pkg/server.getFlows()
      /home/vagrant/go/src/github.com/cilium/hubble/pkg/server/local_observer.go:185 +0x170
  github.com/cilium/hubble/pkg/server.(*LocalObserverServer).GetFlows()
      /home/vagrant/go/src/github.com/cilium/hubble/pkg/server/local_observer.go:162 +0x66
  github.com/cilium/hubble/api/v1/observer._Observer_GetFlows_Handler()
      /home/vagrant/go/src/github.com/cilium/hubble/api/v1/observer/observer.pb.go:714 +0x135
  google.golang.org/grpc.(*Server).processStreamingRPC()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/server.go:1199 +0x1521
  google.golang.org/grpc.(*Server).handleStream()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/server.go:1279 +0x12d7
  google.golang.org/grpc.(*Server).serveStreams.func1.1()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/server.go:710 +0xc8

Previous write at 0x00c0006801b8 by goroutine 41:
  github.com/cilium/hubble/pkg/container.(*Ring).Write()
      /home/vagrant/go/src/github.com/cilium/hubble/pkg/container/ring.go:99 +0x145
  github.com/cilium/hubble/pkg/server.(*LocalObserverServer).Start()
      /home/vagrant/go/src/github.com/cilium/hubble/pkg/server/local_observer.go:109 +0x567

Goroutine 80 (running) created at:
  google.golang.org/grpc.(*Server).serveStreams.func1()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/server.go:708 +0xb8
  google.golang.org/grpc/internal/transport.(*http2Server).operateHeaders()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/internal/transport/http2_server.go:432 +0x1679
  google.golang.org/grpc/internal/transport.(*http2Server).HandleStreams()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/internal/transport/http2_server.go:473 +0x3d7
  google.golang.org/grpc.(*Server).serveStreams()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/server.go:706 +0x19a
  google.golang.org/grpc.(*Server).handleRawConn.func1()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/google.golang.org/grpc/server.go:668 +0x4c

Goroutine 41 (running) created at:
  github.com/cilium/hubble/pkg/server.(*ObserverServer).Start()
      /home/vagrant/go/src/github.com/cilium/hubble/pkg/server/observer.go:77 +0x92
  github.com/cilium/hubble/cmd/serve.New.func1()
      /home/vagrant/go/src/github.com/cilium/hubble/cmd/serve/serve.go:103 +0x9a0
  github.com/spf13/cobra.(*Command).execute()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/github.com/spf13/cobra/command.go:830 +0x8e0
  github.com/spf13/cobra.(*Command).ExecuteC()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/github.com/spf13/cobra/command.go:914 +0x41a
  github.com/cilium/hubble/cmd.Execute()
      /home/vagrant/go/src/github.com/cilium/hubble/vendor/github.com/spf13/cobra/command.go:864 +0x8b
  main.main()
      /home/vagrant/go/src/github.com/cilium/hubble/main.go:22 +0x2f
```
I didn't take time to investigate yet but opened this issue to keep track of it as at first glances it seems to be a different one that the one in #82.

### PR DESCRIPTION
**Pull request by Rolinh**
Make sure to atomic load `r.write` and get rid of `r.full` altogether as it was only used in `Len()` and not stricly necessary.
This fixes a data race on `r.full` as it wasn't atomically updated.

Fixes #140

### CODE REVIEW

File: pkg/container/ring.go [hunk 1]
```diff
@@ -40,9 +40,6 @@ type Ring struct {
 	cycleMask uint64
 	// dataLen is the length of the internal buffer.
 	dataLen uint64
-	// ring is at full capacity and will not overwrite oldest elements by
```
Comment (glibsm) [inline pkg/container/ring.go]: this comment was wrong anyways s/not/now/
